#spring:
#  profiles:
#    include: oauth, real-db
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL57Dialect
#        storage_engine: innodb
#  session:
#    store-type: jdbc


spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://zerowaste-webservice.c8zl7krsxwim.ap-northeast-2.rds.amazonaws.com:3306/zerowaste_webservice
      username: ss
      password: gkrth6933!!
      driver-class-name: org.mariadb.jdbc.Driver